name: weewun
favicon: null
layout_spectrum: 0.16879015951417387
typography_spectrum: 0.4752758969552815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.41741860029287636
  lightness: 0.03931966540403664
  saturation: 0.8090205832850188
  rhythmicContrast: 0.7348928425926715
purpose: []
